name: Send Attendance Message

on:
  schedule:
    - cron: '0 1 * * 0'  # 매주 일요일 10시
  workflow_dispatch: # 수동 실행도 가능하도록 설정

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -U discord.py

      - name: Run the bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python main.py
